runtime: python313

env_variables:
  # API Configuration
  JWT_SECRET_KEY: "crow-eye-secret-key-change-in-production"
  
  # CORS Origins (update with your actual domains)
  CORS_ORIGINS: "http://localhost:3000,https://crowseye.tech,https://*.crowseye.tech,https://*.firebaseapp.com,https://*.web.app"
  
  # Optional: Add your database URL when ready
  # DATABASE_URL: "postgresql://user:pass@host:5432/dbname"

# Basic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2 