runtime: python39

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  # Set your environment variables here
  ENVIRONMENT: "production"
  API_VERSION: "1.0.0"

handlers:
- url: /.*
  script: auto
  secure: always

# Enable CORS for API
- url: /.*
  http_headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers: "Authorization, Content-Type"

# Health check configuration
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# Entrypoint
entrypoint: uvicorn crow_eye_api.main:app --host 0.0.0.0 --port $PORT